# Generated by Django 4.1.4 on 2023-01-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_comment_options_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
